name: replace-in-files
files:
  - 'src/**/*.{js,jsx,ts,tsx}'
  - '.*'
  - '!node_modules'
  - '!config.yaml'
replacements:
  - from: 'aaa'
    to: 'AAA'
  - from: 'env:HOME'
    to: '${env:HOME}'
  - from: 'pkg:VERSION'
    to: '${pkg:version}'
