name: replace-in-files
dryRun: false
files:
  - '**/*'
  - '!node_modules/**'
  - '!dist/**'
replacements:
  - from: 'http://localhost:3000'
    to: 'https://www.example.com:3000'
  - from: 'http://localhost:3001'
    to: 'https://www.example.com:3001'
