name: replace-in-files
files:
  - 'src/**/*.js'
  - '.*'
  - '*'
  - '!node_modules'
  - '!rif.config.yaml'
replacements:
  - from: /aaa/g
    to: AAA
  - item: '${env.HOME}'
  - item: '${pkg.version}'
  - from: __USAGE__
    to: $(rifc -h)
