name: replace-in-files
files:
  - 'src/**/*.js'
  - '.*'
  - '*'
  - '!node_modules'
  - '!rif.config.yaml'
replacements:
  - from: /aaa/g
    to: AAA
  - from: '${env.HOME}'
  - from: '${pkg.version}'
